// Mocks generated by Mockito 5.4.6 from annotations
// in felo_na/test/features/messaging/presentation/bloc/messaging_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:felo_na/core/errors/failures.dart' as _i5;
import 'package:felo_na/features/messaging/domain/entities/conversation.dart'
    as _i6;
import 'package:felo_na/features/messaging/domain/entities/message.dart' as _i7;
import 'package:felo_na/features/messaging/domain/repositories/messaging_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MessagingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessagingRepository extends _i1.Mock
    implements _i3.MessagingRepository {
  MockMessagingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Conversation>>>
  getConversations() =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.Conversation>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Conversation>>(
                    this,
                    Invocation.method(#getConversations, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Conversation>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.Message>>> getMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [conversationId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.Message>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.Message>>(
                    this,
                    Invocation.method(#getMessages, [conversationId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.Message>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Conversation>>
  getOrCreateConversation({
    required String? listingId,
    required String? sellerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateConversation, [], {
              #listingId: listingId,
              #sellerId: sellerId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Conversation>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Conversation>(
                    this,
                    Invocation.method(#getOrCreateConversation, [], {
                      #listingId: listingId,
                      #sellerId: sellerId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Conversation>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.Message>> sendMessage({
    required String? conversationId,
    required String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #conversationId: conversationId,
              #content: content,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.Message>>.value(
              _FakeEither_0<_i5.Failure, _i7.Message>(
                this,
                Invocation.method(#sendMessage, [], {
                  #conversationId: conversationId,
                  #content: content,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.Message>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> markAsRead(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [conversationId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#markAsRead, [conversationId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
