// Mocks generated by Mockito 5.4.6 from annotations
// in felo_na/test/features/messaging/data/repositories/messaging_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:felo_na/features/messaging/data/datasources/messaging_remote_data_source.dart'
    as _i4;
import 'package:felo_na/features/messaging/data/models/conversation_model.dart'
    as _i2;
import 'package:felo_na/features/messaging/data/models/message_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConversationModel_0 extends _i1.SmartFake
    implements _i2.ConversationModel {
  _FakeConversationModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageModel_1 extends _i1.SmartFake implements _i3.MessageModel {
  _FakeMessageModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MessagingRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessagingRemoteDataSource extends _i1.Mock
    implements _i4.MessagingRemoteDataSource {
  MockMessagingRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.ConversationModel>> getConversations() =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, []),
            returnValue: _i5.Future<List<_i2.ConversationModel>>.value(
              <_i2.ConversationModel>[],
            ),
          )
          as _i5.Future<List<_i2.ConversationModel>>);

  @override
  _i5.Future<List<_i3.MessageModel>> getMessages(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [conversationId]),
            returnValue: _i5.Future<List<_i3.MessageModel>>.value(
              <_i3.MessageModel>[],
            ),
          )
          as _i5.Future<List<_i3.MessageModel>>);

  @override
  _i5.Future<_i2.ConversationModel> getOrCreateConversation({
    required String? listingId,
    required String? sellerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateConversation, [], {
              #listingId: listingId,
              #sellerId: sellerId,
            }),
            returnValue: _i5.Future<_i2.ConversationModel>.value(
              _FakeConversationModel_0(
                this,
                Invocation.method(#getOrCreateConversation, [], {
                  #listingId: listingId,
                  #sellerId: sellerId,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.ConversationModel>);

  @override
  _i5.Future<_i3.MessageModel> sendMessage({
    required String? conversationId,
    required String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #conversationId: conversationId,
              #content: content,
            }),
            returnValue: _i5.Future<_i3.MessageModel>.value(
              _FakeMessageModel_1(
                this,
                Invocation.method(#sendMessage, [], {
                  #conversationId: conversationId,
                  #content: content,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.MessageModel>);

  @override
  _i5.Future<void> markAsRead(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [conversationId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
