// Mocks generated by Mockito 5.4.6 from annotations
// in felo_na/test/features/ai/presentation/bloc/ai_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i7;

import 'package:dartz/dartz.dart' as _i2;
import 'package:felo_na/core/errors/failures.dart' as _i5;
import 'package:felo_na/features/ai/domain/entities/scan_result.dart' as _i6;
import 'package:felo_na/features/ai/domain/repositories/ai_repository.dart'
    as _i3;
import 'package:felo_na/features/ai/domain/usecases/chat_usecase.dart' as _i9;
import 'package:felo_na/features/ai/domain/usecases/scan_waste_usecase.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiRepository_1 extends _i1.SmartFake implements _i3.AiRepository {
  _FakeAiRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiRepository extends _i1.Mock implements _i3.AiRepository {
  MockAiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ScanResult>> scanWaste(
    _i7.Uint8List? imageBytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#scanWaste, [imageBytes]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ScanResult>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ScanResult>(
                    this,
                    Invocation.method(#scanWaste, [imageBytes]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ScanResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> chat(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#chat, [message]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#chat, [message]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  void resetChat() => super.noSuchMethod(
    Invocation.method(#resetChat, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ScanWasteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockScanWasteUseCase extends _i1.Mock implements _i8.ScanWasteUseCase {
  MockScanWasteUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AiRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAiRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.AiRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ScanResult>> call(
    _i8.ScanWasteParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ScanResult>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ScanResult>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ScanResult>>);
}

/// A class which mocks [ChatUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatUseCase extends _i1.Mock implements _i9.ChatUseCase {
  MockChatUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AiRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAiRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.AiRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> call(_i9.ChatParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
}
