// Mocks generated by Mockito 5.4.6 from annotations
// in felo_na/test/features/eco_score/data/repositories/eco_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:felo_na/features/eco_score/data/datasources/eco_remote_data_source.dart'
    as _i3;
import 'package:felo_na/features/eco_score/data/models/eco_stats_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEcoStatsModel_0 extends _i1.SmartFake implements _i2.EcoStatsModel {
  _FakeEcoStatsModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EcoRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEcoRemoteDataSource extends _i1.Mock
    implements _i3.EcoRemoteDataSource {
  MockEcoRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.EcoStatsModel> getEcoStats() =>
      (super.noSuchMethod(
            Invocation.method(#getEcoStats, []),
            returnValue: _i4.Future<_i2.EcoStatsModel>.value(
              _FakeEcoStatsModel_0(this, Invocation.method(#getEcoStats, [])),
            ),
          )
          as _i4.Future<_i2.EcoStatsModel>);

  @override
  _i4.Future<List<_i2.PointHistoryModel>> getPointHistory({
    int? page,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPointHistory, [], {
              #page: page,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i2.PointHistoryModel>>.value(
              <_i2.PointHistoryModel>[],
            ),
          )
          as _i4.Future<List<_i2.PointHistoryModel>>);

  @override
  _i4.Future<_i2.EcoStatsModel> addPoints({
    required int? points,
    required String? reason,
    String? relatedId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addPoints, [], {
              #points: points,
              #reason: reason,
              #relatedId: relatedId,
            }),
            returnValue: _i4.Future<_i2.EcoStatsModel>.value(
              _FakeEcoStatsModel_0(
                this,
                Invocation.method(#addPoints, [], {
                  #points: points,
                  #reason: reason,
                  #relatedId: relatedId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.EcoStatsModel>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getLeaderboard({int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getLeaderboard, [], {#limit: limit}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);
}
