// File generated by FlutterFire CLI — manually completed for web support.
// Run `flutterfire configure` to regenerate after adding iOS/Web apps in Firebase Console.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS. '
          'Run `flutterfire configure` to generate iOS options.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS. '
          'Run `flutterfire configure` to generate macOS options.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows. '
          'Run `flutterfire configure` to generate Windows options.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux. '
          'Run `flutterfire configure` to generate Linux options.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── Android ──────────────────────────────────────────────────────────
  // Values sourced from android/app/google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAbRDyGgXLkwyMtC-fz3e1vGqGsyG1k98',
    appId: '1:1062477866360:android:18a95740dd3341fdd5148d',
    messagingSenderId: '1062477866360',
    projectId: 'felona-72453',
    storageBucket: 'felona-72453.firebasestorage.app',
  );

  // ─── Web ──────────────────────────────────────────────────────────────
  // NOTE: Add a Web app in Firebase Console, then replace these placeholder
  // values with the real config from Project Settings → Your apps → Web.
  // Until then, the app runs without Firebase on web (graceful degradation).
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAbRDyGgXLkwyMtC-fz3e1vGqGsyG1k98',
    appId: '1:1062477866360:web:REPLACE_WITH_REAL_WEB_APP_ID',
    messagingSenderId: '1062477866360',
    projectId: 'felona-72453',
    storageBucket: 'felona-72453.firebasestorage.app',
    // authDomain: 'felona-72453.firebaseapp.com',
    // measurementId: 'G-XXXXXXXXXX',  // fill after enabling Analytics
  );
}
