// Mocks generated by Mockito 5.4.6 from annotations
// in felo_na/test/features/eco_score/presentation/bloc/eco_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:felo_na/core/errors/failures.dart' as _i5;
import 'package:felo_na/features/eco_score/domain/entities/eco_stats.dart'
    as _i6;
import 'package:felo_na/features/eco_score/domain/repositories/eco_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EcoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEcoRepository extends _i1.Mock implements _i3.EcoRepository {
  MockEcoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.EcoStats>> getEcoStats() =>
      (super.noSuchMethod(
            Invocation.method(#getEcoStats, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.EcoStats>>.value(
                  _FakeEither_0<_i5.Failure, _i6.EcoStats>(
                    this,
                    Invocation.method(#getEcoStats, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.EcoStats>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PointHistory>>> getPointHistory({
    int? page,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPointHistory, [], {
              #page: page,
              #limit: limit,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.PointHistory>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.PointHistory>>(
                    this,
                    Invocation.method(#getPointHistory, [], {
                      #page: page,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.PointHistory>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.EcoStats>> addPoints({
    required int? points,
    required String? reason,
    String? relatedId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addPoints, [], {
              #points: points,
              #reason: reason,
              #relatedId: relatedId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.EcoStats>>.value(
                  _FakeEither_0<_i5.Failure, _i6.EcoStats>(
                    this,
                    Invocation.method(#addPoints, [], {
                      #points: points,
                      #reason: reason,
                      #relatedId: relatedId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.EcoStats>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>
  getLeaderboard({int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getLeaderboard, [], {#limit: limit}),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<Map<String, dynamic>>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#getLeaderboard, [], {#limit: limit}),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>);
}
