// Mocks generated by Mockito 5.4.6 from annotations
// in felo_na/test/features/marketplace/presentation/bloc/marketplace_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:felo_na/core/constants/enums.dart' as _i7;
import 'package:felo_na/core/errors/failures.dart' as _i5;
import 'package:felo_na/features/marketplace/domain/entities/listing.dart'
    as _i6;
import 'package:felo_na/features/marketplace/domain/repositories/marketplace_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MarketplaceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarketplaceRepository extends _i1.Mock
    implements _i3.MarketplaceRepository {
  MockMarketplaceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Listing>>> getListings({
    int? page,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getListings, [], {#page: page, #limit: limit}),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Listing>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Listing>>(
                    this,
                    Invocation.method(#getListings, [], {
                      #page: page,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Listing>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Listing>>> getListingsByCategory(
    _i7.ListingCategory? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getListingsByCategory, [category]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Listing>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Listing>>(
                    this,
                    Invocation.method(#getListingsByCategory, [category]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Listing>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Listing>>> searchListings(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchListings, [query]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Listing>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Listing>>(
                    this,
                    Invocation.method(#searchListings, [query]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Listing>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Listing>> createListing({
    required String? title,
    required String? description,
    required double? price,
    required _i7.ListingCategory? category,
    required List<String>? imagePaths,
    String? location,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createListing, [], {
              #title: title,
              #description: description,
              #price: price,
              #category: category,
              #imagePaths: imagePaths,
              #location: location,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Listing>>.value(
              _FakeEither_0<_i5.Failure, _i6.Listing>(
                this,
                Invocation.method(#createListing, [], {
                  #title: title,
                  #description: description,
                  #price: price,
                  #category: category,
                  #imagePaths: imagePaths,
                  #location: location,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Listing>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Listing>>> getMyListings() =>
      (super.noSuchMethod(
            Invocation.method(#getMyListings, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Listing>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Listing>>(
                    this,
                    Invocation.method(#getMyListings, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Listing>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> toggleFavorite(String? listingId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [listingId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#toggleFavorite, [listingId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Listing>> getListingById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getListingById, [id]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Listing>>.value(
              _FakeEither_0<_i5.Failure, _i6.Listing>(
                this,
                Invocation.method(#getListingById, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Listing>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteListing(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteListing, [id]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteListing, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Listing>>> getSellerListings(
    String? sellerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSellerListings, [sellerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Listing>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Listing>>(
                    this,
                    Invocation.method(#getSellerListings, [sellerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Listing>>>);
}
